CREATE DATABASE PRJ;

USE PRJ;

CREATE TABLE player (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nickName VARCHAR(200) NOT NULL ,
    ancestry VARCHAR(50) NOT NULL ,
    class VARCHAR(50) NOT NULL ,
    level INT NOT NULL ,
    religion VARCHAR(50) NOT NULL



);

